kind: ConfigMap
metadata:
  name: kafka-manager-config
  namespace: kafka
apiVersion: v1
data:
  init.sh: |-
    #!/bin/sh

    if [[ $KM_USERNAME != ''  && $KM_PASSWORD != '' ]]; then
        sed -i.bak '/^basicAuthentication/d' /kafka-manager-${KM_VERSION}/conf/application.conf
        echo 'basicAuthentication.enabled=true' >> /kafka-manager-${KM_VERSION}/conf/application.conf
        echo "basicAuthentication.username=${KM_USERNAME}" >> /kafka-manager-${KM_VERSION}/conf/application.conf
        echo "basicAuthentication.password=${KM_PASSWORD}" >> /kafka-manager-${KM_VERSION}/conf/application.conf
        echo 'basicAuthentication.realm="Kafka-Manager"' >> /kafka-manager-${KM_VERSION}/conf/application.conf
    fi
